# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# -------- Smoothness overrides --------

misc {
    vrr = 0
    vfr = true
}

cursor {
    no_hardware_cursors = false
}

render {
    direct_scanout = true
}

decoration {
    blur {
        size = 6
        passes = 2
    }

    shadow {
        range = 20
        render_power = 4
    }

    dim_strength = 0.03
}

# Snappier animations
animation = windowsIn, 1, 2.5, emphasizedDecel, popin 80%
animation = fadeIn, 1, 2.5, emphasizedDecel
animation = windowsOut, 1, 1.5, emphasizedDecel, popin 90%
animation = fadeOut, 1, 1.5, emphasizedDecel
animation = windowsMove, 1, 2.5, emphasizedDecel, slide
animation = layersIn, 1, 2, emphasizedDecel, popin 93%
animation = layersOut, 1, 1.8, menu_accel, popin 94%
animation = workspaces, 1, 5, menu_decel, slide
animation = specialWorkspaceIn, 1, 2.2, emphasizedDecel, slidevert
animation = specialWorkspaceOut, 1, 1, emphasizedAccel, slidevert
