$text_color = rgba({{ primaryFixed.hex }}FF)
$entry_background_color = rgba({{ onPrimaryFixed.hex }}11)
$entry_border_color = rgba({{ outline.hex }}55)
$entry_color = rgba({{ primaryFixed.hex }}FF)
$font_family = JetBrains Mono
$font_family_clock = JetBrains Mono
$font_material_symbols = Material Symbols Rounded
